SELECT BUSINESS_CAT_ID,SUM(REVIEW_COUNTS) FROM (SELECT R.REVIEW_COUNTS,B.BUSINESS_ID,B.BUSINESS_CAT_ID FROM 
(SELECT COUNT(REVIEW_ID)AS REVIEW_COUNTS,BUSINESS_ID FROM REVIEWS
GROUP BY BUSINESS_ID ORDER BY REVIEW_COUNTS DESC) R,BUSINESS B
WHERE R.BUSINESS_ID = B.BUSINESS_ID) RESULT GROUP BY BUSINESS_CAT_ID
ORDER BY SUM(REVIEW_COUNTS) DESC;

