SELECT * FROM
(SELECT DISTINCT PERCENTAGE,BUSINESS_CAT_ID FROM 
(SELECT A.PERCENTAGE,B.BUSINESS_ID,B.BUSINESS_CAT_ID FROM 
(SELECT (AVG(RATING)/5)*100 AS PERCENTAGE,BUSINESS_ID FROM REVIEWS GROUP BY BUSINESS_ID ORDER BY PERCENTAGE DESC) A,
(SELECT BUSINESS_ID,BUSINESS_CAT_ID FROM BUSINESS ) B WHERE A.BUSINESS_ID = B.BUSINESS_ID ORDER BY A.PERCENTAGE DESC) ORDER BY PERCENTAGE DESC) WHERE ROWNUM <=2;
