SELECT * FROM (SELECT B.BUSINESS_ID,B.BUSINESS_NAME,A.REVIEW_COUNT,A.REVIEW_PERCENTAGE FROM 
(SELECT ((AVG(RATING)/5)*100) AS REVIEW_PERCENTAGE,COUNT(REVIEW_ID) AS REVIEW_COUNT,BUSINESS_ID 
FROM REVIEWS
GROUP BY BUSINESS_ID) A,(SELECT * FROM BUSINESS WHERE CITY='San Jose' AND STATE='CA') B
WHERE A.BUSINESS_ID = B.BUSINESS_ID AND A.REVIEW_COUNT>=5 ORDER BY REVIEW_PERCENTAGE DESC) WHERE ROWNUM <=5;
