SELECT BB.BUSINESS_ID,BB.BUSINESS_NAME,D.PERCENTAGE_OF_REVIEW,BB.CITY,BB.STATE,BB.BUSINESS_CAT_ID,BB.PHONE_NO,BB.STATUS FROM (SELECT A.BUSINESS_ID,((A.BUSINSS_COUNT/R.TOTAL_COUNT)*100) AS PERCENTAGE_OF_REVIEW FROM (SELECT COUNT(R.REVIEW_ID) AS BUSINSS_COUNT,B.BUSINESS_ID,RATING
FROM BUSINESS B ,REVIEWS R
WHERE B.BUSINESS_ID = R.BUSINESS_ID AND B.CITY='San Jose' and B.STATE='CA' 
GROUP BY B.BUSINESS_ID,RATING
HAVING RATING=5 AND COUNT(R.REVIEW_ID) >4) A , 
(SELECT COUNT(REVIEW_ID) AS TOTAL_COUNT FROM REVIEWS) R ORDER BY PERCENTAGE_OF_REVIEW DESC)D,BUSINESS BB WHERE D.BUSINESS_ID=BB.BUSINESS_ID AND ROWNUM <=5;

OR 

SELECT * FROM (
SELECT ((B.EACH_BUS_COUNT/A.TOTAL_COUNT)*100) AS PERCENTAGE_OF_REVIEWS ,B.BUSINESS_ID FROM (
SELECT COUNT(REVIEW_ID) AS TOTAL_COUNT FROM REVIEWS) A,(
SELECT COUNT(REVIEW_ID) AS EACH_BUS_COUNT,BUSINESS_ID FROM (
SELECT * FROM REVIEWS WHERE RATING =5) 
GROUP BY BUSINESS_ID HAVING COUNT(REVIEW_ID) > 4 ORDER BY EACH_BUS_COUNT DESC) B ORDER BY PERCENTAGE_OF_REVIEWS DESC ) C ,
(SELECT * FROM BUSINESS WHERE CITY='San Jose' AND STATE='CA' ) D WHERE C.BUSINESS_ID = D.BUSINESS_ID;
