SELECT B.BUSINESS_ID,B.BUSINESS_NAME,C.BUSINESS_REVIEW_COUNT,C.RATING,A.REVIEWED_BY_NO_OF_ELITE_USERS FROM (
SELECT * FROM (
SELECT SUM(ELITE_USERS.REVIEW_COUNT)AS BUSINESS_REVIEW_COUNT,COUNT(ELITE_USERS.AUTHOR)AS REVIEWED_BY_NO_OF_ELITE_USERS,R.BUSINESS_ID FROM (
SELECT * FROM (SELECT COUNT(REVIEW_ID) AS REVIEW_COUNT,AUTHOR FROM REVIEWS GROUP BY AUTHOR ORDER BY REVIEW_COUNT DESC) WHERE REVIEW_COUNT >10) ELITE_USERS , REVIEWS R WHERE ELITE_USERS.AUTHOR = R.AUTHOR 
GROUP BY R.BUSINESS_ID ORDER BY REVIEWED_BY_NO_OF_ELITE_USERS DESC) WHERE REVIEWED_BY_NO_OF_ELITE_USERS > 5) A, BUSINESS B,(
SELECT AVG(RATING)AS RATING,COUNT(REVIEW_ID) AS BUSINESS_REVIEW_COUNT,BUSINESS_ID FROM REVIEWS GROUP BY BUSINESS_ID) C
WHERE A.BUSINESS_ID = B.BUSINESS_ID AND C.BUSINESS_ID = B.BUSINESS_ID AND ROWNUM<=5;
