SELECT A.YELP_ID,A.FIRST_NAME,A.LAST_NAME,B.GENDER,A.AGE,B.BIRTHDATE,B.BIRTHPLACE,B.EMAIL_ID FROM
(SELECT FLOOR(MONTHS_BETWEEN(SYSDATE,BIRTHDATE)/12) AS AGE,YELP_ID,FIRST_NAME,LAST_NAME FROM YELP_USER ORDER BY AGE DESC) A,
(SELECT * FROM YELP_USER Y WHERE 
NOT EXISTS (SELECT * FROM (SELECT DISTINCT COUNT(REVIEW_ID) AS REVIEW_COUNT,AUTHOR FROM REVIEWS GROUP BY AUTHOR ORDER BY REVIEW_COUNT)A WHERE Y.YELP_ID= A.AUTHOR )) B
WHERE A.YELP_ID = B.YELP_ID AND ROWNUM<=1 ORDER BY AGE DESC; 
