SELECT BB.BUSINESS_ID,BB.BUSINESS_NAME,D.PERCENTAGE_OF_RATING_AS_FIVE,BB.CITY,BB.STATE,BB.BUSINESS_CAT_ID,BB.PHONE_NO,BB.STATUS FROM (
SELECT C.BUSINESS_ID ,((RATED_ABOVE_FIVE/REVIEW_COUNT)*100) AS PERCENTAGE_OF_RATING_AS_FIVE FROM (SELECT B.BUSINESS_ID,COUNT(R.REVIEW_ID) AS REVIEW_COUNT
FROM BUSINESS B,REVIEWS R
WHERE B.BUSINESS_ID = R.BUSINESS_ID
GROUP BY B.BUSINESS_ID 
HAVING COUNT(R.REVIEW_ID) > 4
ORDER BY REVIEW_COUNT DESC) A ,(SELECT COUNT(REVIEW_ID) AS RATED_ABOVE_FIVE,BUSINESS_ID FROM (SELECT * FROM REVIEWS WHERE RATING >=5) GROUP BY BUSINESS_ID) C
WHERE A.BUSINESS_ID = C.BUSINESS_ID ORDER BY PERCENTAGE_OF_RATING_AS_FIVE DESC) D ,BUSINESS BB
WHERE D.BUSINESS_ID = BB.BUSINESS_ID;
