SELECT G.AUTHOR,Y.FIRST_NAME,Y.LAST_NAME,G.NO_OF_DIFFERENT_STATE,G.STATES_REVIEWED_FOR FROM(SELECT AUTHOR,NO_OF_DIFFERENT_STATE,STATES_REVIEWED_FOR FROM (SELECT  D.AUTHOR,COUNT(D.STATE)AS NO_OF_DIFFERENT_STATE,LISTAGG(D.STATE,',') WITHIN GROUP(ORDER BY STATE DESC) AS STATES_REVIEWED_FOR FROM (SELECT DISTINCT F.AUTHOR, STATE FROM (SELECT * FROM (SELECT A.AUTHOR,R.BUSINESS_ID FROM(SELECT * FROM (SELECT COUNT(BUSINESS_ID) AS REVIEWED_COUT, AUTHOR 
FROM REVIEWS
GROUP BY AUTHOR)WHERE REVIEWED_COUT >2 ORDER BY REVIEWED_COUT) A, REVIEWS R WHERE A.AUTHOR = R.AUTHOR) C , BUSINESS B 
WHERE C.BUSINESS_ID = B.BUSINESS_ID) F ) D GROUP BY D.AUTHOR) WHERE NO_OF_DIFFERENT_STATE >= 3 ORDER BY AUTHOR)G ,YELP_USER Y WHERE G.AUTHOR = Y.YELP_ID;
